### ISSUE TITLE
Préalable Séquences & Dépendances externes

### ISSUE THREAD

**Issue by DevUpon** [Oxydev-Software/Oxydom#16]

**Comment by avorane** [comment]
A finir après concertation avec rémi. Fais ce samedi 26/08 les dépendances externes

**Comment by avorane** [comment]
Préalables séquences. Je me demande si il ne s'agit pas de séquences du point de vue gestion de projet. On découpe le projet en séquences.

**Comment by daynox** [comment]
Nicolas demande à Remi ou Benoit Marchal lundi pour préalable à la réalisation des séquences.
