### ISSUE TITLE
Environnement de développement de l'App

### ISSUE THREAD

**Issue by DevUpon** [Oxydev-Software/Oxydom#20]
La définition de l’environnement de développement de l’application

**Comment by Linkyu** [comment]
Description à expliciter.

**Comment by Linkyu** [comment]
Ne peut pas être fait avant le choix technique.

**Comment by daynox** [comment]
- Backend - Django/Python :
VS / VSC / Pycharm
Atom
 - 3D - Unreal :
VS / VSC - Plugin Visual assiste avec une autocompletion pour les modules Unreal
CLion - Bug en cours de résolution
 - Front - JS/HTML/CSS : 
VS / VSC / Pycharm
