### ISSUE TITLE
Méthode de développement

### ISSUE THREAD

**Issue by DevUpon** [Oxydev-Software/Oxydom#21]
La méthode de développement qui vous parait la mieux adaptée à la typologie et à la taille du
projet.

**Comment by Linkyu** [comment]
Nous avons choisi une méthode de développement agile, reposant sur un cycle de développeent itératif, avec des réunions hebdomadaires pour monitorer l'avancement et adapter les tâches suivantes. Il est prévu qu'une version de dev soit intégré tous les 4 sprints (~1/mois).
La gestion de conf du code serva versionné sur un principe de Gitflow Worklow, avec une branche master à merge request par vote, une branche de dev, et plusieurs branches features.
